name: tf_MS3
channels:
  - defaults
dependencies:
  - python=3.6
  - pip
  - jupyter
  - pandas
  - seaborn
  - pydot
  - graphviz
  - pip:
    - tf-nightly
    - tensorflow-model-optimization
    - bluepy
    - west
    - bleak
