
/* AUTO-GENERATED by gen_isr_tables.py, do not edit! */

#include <toolchain.h>
#include <linker/sections.h>
#include <sw_isr_table.h>
#include <arch/cpu.h>

#if defined(CONFIG_GEN_SW_ISR_TABLE) && defined(CONFIG_GEN_IRQ_VECTOR_TABLE)
#define ISR_WRAPPER ((uint32_t)&_isr_wrapper)
#else
#define ISR_WRAPPER NULL
#endif

uint32_t __irq_vector_table _irq_vector_table[30] = {
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	16935421,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	16935365,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	16935395,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
};
struct _isr_table_entry __sw_isr_table _sw_isr_table[30] = {
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x1026a27, (void *)0x1026a2b},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)0x10222f9},
	{(const void *)0x0, (void *)0x1021e91},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x1022f11, (void *)0x1026a2b},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)0x1022d2d},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)0x1020729},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
};
