
/* AUTO-GENERATED by gen_isr_tables.py, do not edit! */

#include <toolchain.h>
#include <linker/sections.h>
#include <sw_isr_table.h>
#include <arch/cpu.h>

#if defined(CONFIG_GEN_SW_ISR_TABLE) && defined(CONFIG_GEN_IRQ_VECTOR_TABLE)
#define ISR_WRAPPER ((uint32_t)&_isr_wrapper)
#else
#define ISR_WRAPPER NULL
#endif

uint32_t __irq_vector_table _irq_vector_table[30] = {
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	16936931,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	16936875,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	16936905,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
	ISR_WRAPPER,
};
struct _isr_table_entry __sw_isr_table _sw_isr_table[30] = {
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x102700d, (void *)0x1027011},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)0x10227ad},
	{(const void *)0x0, (void *)0x1022345},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x10234a5, (void *)0x1027011},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)0x10232c1},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)0x1020bdd},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
	{(const void *)0x0, (void *)&z_irq_spurious},
};
